#!/bin/bash

if [[ $(whoami) != "root" ]]; then
    echo "Must be run as root!"
    exit 1
fi

#stuff to setup OMNIPLAY_DIR
user=$(who am i | awk '{print $1}')
setupfile=$(sudo -H -u $user echo $HOME/.omniplay_setup) 

source $setupfile

function do_make() {
	local rc;
	sudo -H -u $user KCONFIG_CONFIG=.config make -j$build_parallel 2>&1 | tee errlog
	return ${PIPESTATUS[0]}
}

ret=0

num_cores=`cat /proc/cpuinfo | grep processor | wc -l`
build_parallel=$(($num_cores+1))
do_make

rc=$?

if [ $rc -eq 0 ]; then
    make install

	if [[ ! -z $OMNIPLAY_DIR ]]; then
	        make headers_install INSTALL_HDR_PATH=$OMNIPLAY_DIR/test/replay_headers
		echo "Building files depending on kernel headers"
		pushd $OMNIPLAY_DIR/test &> /dev/null
		sudo -H -u $user make
		pushd dev &> /dev/null
		sudo -H -u $user make 
		make install
		popd &> /dev/null
		popd &> /dev/null
	else
		echo "WARNING: OMNIPLAY_DIR environment variable not set (run scripts/setup.sh)"
		echo "    Headers not installed, tests not rebuilt!"
	fi
else
	echo "Make Failure!"
	ret=1
fi

# Beep!
echo -e "\a"

exit $ret

