#include <linux/c_constants.h>

const unsigned int PARTIAL_INT_MASK[33] = {

0x00000000, 0x00000001, 0x00000003, 0x00000007, 0x0000000f, 0x0000001f,
		0x0000003f, 0x0000007f, 0x000000ff, 0x000001ff, 0x000003ff, 0x000007ff,
		0x00000fff, 0x00001fff, 0x00003fff, 0x00007fff, 0x0000ffff, 0x0001ffff,
		0x0003ffff, 0x0007ffff, 0x000fffff, 0x001fffff, 0x003fffff, 0x007fffff,
		0x00ffffff, 0x01ffffff, 0x03ffffff, 0x07ffffff, 0x0fffffff, 0x1fffffff,
		0x3fffffff, 0x7fffffff, 0xffffffff

};

const char* XPROTO_TABLE[128] = { "0", "X_CreateWindow ",
		"X_ChangeWindowAttributes ", "X_GetWindowAttributes ",
		"X_DestroyWindow ", "X_DestroySubwindows ", "X_ChangeSaveSet ",
		"X_ReparentWindow ", "X_MapWindow ", "X_MapSubwindows ",
		"X_UnmapWindow ", "X_UnmapSubwindows ", "X_ConfigureWindow ",
		"X_CirculateWindow ", "X_GetGeometry ", "X_QueryTree ",
		"X_InternAtom ", "X_GetAtomName ", "X_ChangeProperty ",
		"X_DeleteProperty ", "X_GetProperty ", "X_ListProperties ",
		"X_SetSelectionOwner ", "X_GetSelectionOwner ", "X_ConvertSelection ",
		"X_SendEvent ", "X_GrabPointer ", "X_UngrabPointer ", "X_GrabButton ",
		"X_UngrabButton ", "X_ChangeActivePointerGrab ", "X_GrabKeyboard ",
		"X_UngrabKeyboard ", "X_GrabKey ", "X_UngrabKey ", "X_AllowEvents ",
		"X_GrabServer ", "X_UngrabServer ", "X_QueryPointer ",
		"X_GetMotionEvents ", "X_TranslateCoords ", "X_WarpPointer ",
		"X_SetInputFocus ", "X_GetInputFocus ", "X_QueryKeymap ",
		"X_OpenFont ", "X_CloseFont ", "X_QueryFont ", "X_QueryTextExtents ",
		"X_ListFonts ", "X_ListFontsWithInfo ", "X_SetFontPath ",
		"X_GetFontPath ", "X_CreatePixmap ", "X_FreePixmap ", "X_CreateGC ",
		"X_ChangeGC ", "X_CopyGC ", "X_SetDashes ", "X_SetClipRectangles ",
		"X_FreeGC ", "X_ClearArea ", "X_CopyArea ", "X_CopyPlane ",
		"X_PolyPoint ", "X_PolyLine ", "X_PolySegment ", "X_PolyRectangle ",
		"X_PolyArc ", "X_FillPoly ", "X_PolyFillRectangle ", "X_PolyFillArc ",
		"X_PutImage ", "X_GetImage ", "X_PolyText8 ", "X_PolyText16 ",
		"X_ImageText8 ", "X_ImageText16 ", "X_CreateColormap ",
		"X_FreeColormap ", "X_CopyColormapAndFree ", "X_InstallColormap ",
		"X_UninstallColormap ", "X_ListInstalledColormaps ", "X_AllocColor ",
		"X_AllocNamedColor ", "X_AllocColorCells ", "X_AllocColorPlanes ",
		"X_FreeColors ", "X_StoreColors ", "X_StoreNamedColor ",
		"X_QueryColors ", "X_LookupColor ", "X_CreateCursor ",
		"X_CreateGlyphCursor ", "X_FreeCursor ", "X_RecolorCursor ",
		"X_QueryBestSize ", "X_QueryExtension ", "X_ListExtensions ",
		"X_ChangeKeyboardMapping ", "X_GetKeyboardMapping ",
		"X_ChangeKeyboardControl ", "X_GetKeyboardControl ", "X_Bell ",
		"X_ChangePointerControl ", "X_GetPointerControl ", "X_SetScreenSaver ",
		"X_GetScreenSaver ", "X_ChangeHosts ", "X_ListHosts ",
		"X_SetAccessControl ", "X_SetCloseDownMode ", "X_KillClient ",
		"X_RotateProperties ", "X_ForceScreenSaver", "X_SetPointerMapping",
		"X_GetPointerMapping", "X_SetModifierMapping", "X_GetModifierMapping",
		"X_NoOperation"

};

const char* EVENT_TABLE[128] ={
	"0",
	"1",
	"KeyPress	",
	"KeyRelease	",
	"ButtonPress	",
	"ButtonRelease	",
	"MotionNotify	",
	"EnterNotify	",
	"LeaveNotify	",
	"FocusIn	",
	"FocusOut	",
	"KeymapNotify	",
	"Expose	",
	"GraphicsExpose	",
	"NoExpose	",
	"VisibilityNotify	",
	"CreateNotify	",
	"DestroyNotify	",
	"UnmapNotify	",
	"MapNotify	",
	"MapRequest	",
	"ReparentNotify	",
	"ConfigureNotify	",
	"ConfigureRequest	",
	"GravityNotify	",
	"ResizeRequest	",
	"CirculateNotify	",
	"CirculateRequest	",
	"PropertyNotify	",
	"SelectionClear	",
	"SelectionRequest	",
	"SelectionNotify	",
	"ColormapNotify	",
	"ClientMessage	",
	"MappingNotify	",
	"LASTEvent	"

};
